from enum import StrEnum


class SE_OnOff1(StrEnum):
    ON = "on"
    OFF = "off"


class SE_StyleType(StrEnum):
    PARAGRAPH = "paragraph"
    CHARACTER = "character"
    TABLE = "table"
    NUMBERING = "numbering"


class SE_TblStyleOverrideType(StrEnum):
    ENTIRE_TABLE = "wholeTable"
    HEADER_ROW = "firstRow"
    FOOTER_ROW = "lastRow"
    FIRST_COLUMN = "firstCol"
    LAST_COLUMN = "lastCol"
    VERTICAL_BAND_ODD = "band1Vert"
    VERTICAL_BAND_EVEN = "band2Vert"
    HORIZONTAL_BAND_ODD = "band1Horz"
    HORIZONTAL_BAND_EVEN = "band2Horz"
    TOP_RIGHT_CORNER_CELL = "neCell"
    TOP_LEFT_CORNER_CELL = "nwCell"
    BOTTOM_RIGHT_CORNER_CELL = "seCell"
    BOTTOM_LEFT_CORNER_CELL = "swCell"


class SE_Merge(StrEnum):
    CONTINUE = "continue"
    RESTART = "restart"


class SE_VerticalAlignRun(StrEnum):
    BASELINE = "baseline"
    SUPERSCRIPT = "superscript"
    SUBSCRIPT = "subscript"


class SE_UNDERLINE(StrEnum):
    SINGLE = "single"
    WORDS = "words"
    DOUBLE = "double"
    THICK = "thick"
    DOTTED = "dotted"
    DOTTED_HEAVY = "dottedHeavy"
    DASH = "dash"
    DASHED_HEAVY = "dashedHeavy"
    DASH_LONG = "dashLong"
    DASH_LONG_HEAVY = "dashLongHeavy"
    DOT_DASH = "dotDash"
    DASH_DOT_HEAVY = "dashDotHeavy"
    DOT_DOT_DASH = "dotDotDash"
    DASH_DOT_DOT_HEAVY = "dashDotDotHeavy"
    WAVE = "wave"
    WAVY_HEAVY = "wavyHeavy"
    WAVY_DOUBLE = "wavyDouble"
    NONE = "none"


class SE_MultilevelType(StrEnum):
    SINGLE_LEVEL = "singleLevel"
    MULTILEVEL = "multilevel"
    HYBRID_MULTILEVEL = "hybridMultilevel"


class SE_TblWidth(StrEnum):
    NULL = "nil"
    PERCENT = "pct"
    TWIPS = "dxa"
    AUTO = "auto"


class SE_BORDER(StrEnum):
    NULL = "nil"
    NONE = "none"
    SINGLE = "single"
    THICK = "thick"
    DOUBLE = "double"
    DOTTED = "dotted"
    DASHED = "dashed"
    DOT_DASH = "dotDash"
    DOT_DOT_DASH = "dotDotDash"
    TRIPLE = "triple"
    THIN_THICK_SMALL_GAP = "thinThickSmallGap"
    THICK_THIN_SMALL_GAP = "thickThinSmallGap"
    THIN_THICK_THIN_SMALL_GAP = "thinThickThinSmallGap"
    THIN_THICK_MEDIUM_GAP = "thinThickMediumGap"
    THICK_THIN_MEDIUM_GAP = "thickThinMediumGap"
    THIN_THICK_THIN_MEDIUM_GAP = "thinThickThinMediumGap"
    THIN_THICK_LARGE_GAP = "thinThickLargeGap"
    THICK_THIN_LARGE_GAP = "thickThinLargeGap"
    THIN_THICK_THIN_LARGE_GAP = "thinThickThinLargeGap"
    WAVE = "wave"
    DOUBLE_WAVE = "doubleWave"
    DASH_SMALL_GAP = "dashSmallGap"
    DASH_DOT_STROKED = "dashDotStroked"
    THREE_D_EMBOSS = "threeDEmboss"
    THREE_D_ENGRAVE = "threeDEngrave"
    OUTSET = "outset"
    INSET = "inset"
    APPLES = "apples"
    ARCHED_SCALLOPS = "archedScallops"
    BABY_PACIFIER = "babyPacifier"
    BABY_RATTLE = "babyRattle"
    BALLOONS_3_COLORS = "balloons3Colors"
    BALLOONS_HOT_AIR = "balloonsHotAir"
    BASIC_BLACK_DASHES = "basicBlackDashes"
    BASIC_BLACK_DOTS = "basicBlackDots"
    BASIC_BLACK_SQUARES = "basicBlackSquares"
    BASIC_THIN_LINES = "basicThinLines"
    BASIC_WHITE_DASHES = "basicWhiteDashes"
    BASIC_WHITE_DOTS = "basicWhiteDots"
    BASIC_WHITE_SQUARES = "basicWhiteSquares"
    BASIC_WIDE_INLINE = "basicWideInline"
    BASIC_WIDE_MIDLINE = "basicWideMidline"
    BASIC_WIDE_OUTLINE = "basicWideOutline"
    BATS = "bats"
    BIRDS = "birds"
    BIRDS_FLIGHT = "birdsFlight"
    CABINS = "cabins"
    CAKE_SLICE = "cakeSlice"
    CANDY_CORN = "candyCorn"
    CELTIC_KNOTWORK = "celticKnotwork"
    CERTIFICATE_BANNER = "certificateBanner"
    CHAIN_LINK = "chainLink"
    CHAMPAGNE_BOTTLE = "champagneBottle"
    CHECKED_BAR_BLACK = "checkedBarBlack"
    CHECKED_BAR_COLOR = "checkedBarColor"
    CHECKERED = "checkered"
    CHRISTMAS_TREE = "christmasTree"
    CIRCLES_LINES = "circlesLines"
    CIRCLES_RECTANGLES = "circlesRectangles"
    CLASSICAL_WAVE = "classicalWave"
    CLOCKS = "clocks"
    COMPASS = "compass"
    CONFETTI = "confetti"
    CONFETTI_GRAYS = "confettiGrays"
    CONFETTI_OUTLINE = "confettiOutline"
    CONFETTI_STREAMERS = "confettiStreamers"
    CONFETTI_WHITE = "confettiWhite"
    CORNER_TRIANGLES = "cornerTriangles"
    COUPON_CUTOUT_DASHES = "couponCutoutDashes"
    COUPON_CUTOUT_DOTS = "couponCutoutDots"
    CRAZY_MAZE = "crazyMaze"
    CREATURES_BUTTERFLY = "creaturesButterfly"
    CREATURES_FISH = "creaturesFish"
    CREATURES_INSECTS = "creaturesInsects"
    CREATURES_LADY_BUG = "creaturesLadyBug"
    CROSS_STITCH = "crossStitch"
    CUP = "cup"
    DECO_ARCH = "decoArch"
    DECO_ARCH_COLOR = "decoArchColor"
    DECO_BLOCKS = "decoBlocks"
    DIAMONDS_GRAY = "diamondsGray"
    DOUBLE_D = "doubleD"
    DOUBLE_DIAMONDS = "doubleDiamonds"
    EARTH_1 = "earth1"
    EARTH_2 = "earth2"
    EARTH_3 = "earth3"
    ECLIPSING_SQUARES_1 = "eclipsingSquares1"
    ECLIPSING_SQUARES_2 = "eclipsingSquares2"
    EGGS_BLACK = "eggsBlack"
    FANS = "fans"
    FILM = "film"
    FIRECRACKERS = "firecrackers"
    FLOWERS_BLOCK_PRINT = "flowersBlockPrint"
    FLOWERS_DAISIES = "flowersDaisies"
    FLOWERS_MODERN_1 = "flowersModern1"
    FLOWERS_MODERN_2 = "flowersModern2"
    FLOWERS_PANSY = "flowersPansy"
    FLOWERS_RED_ROSE = "flowersRedRose"
    FLOWERS_ROSES = "flowersRoses"
    FLOWERS_TEACUP = "flowersTeacup"
    FLOWERS_TINY = "flowersTiny"
    GEMS = "gems"
    GINGERBREAD_MAN = "gingerbreadMan"
    GRADIENT = "gradient"
    HANDMADE_1 = "handmade1"
    HANDMADE_2 = "handmade2"
    HEART_BALLOON = "heartBalloon"
    HEART_GRAY = "heartGray"
    HEARTS = "hearts"
    HEEBIE_JEEBIES = "heebieJeebies"
    HOLLY = "holly"
    HOUSE_FUNKY = "houseFunky"
    HYPNOTIC = "hypnotic"
    ICE_CREAM_CONES = "iceCreamCones"
    LIGHT_BULB = "lightBulb"
    LIGHTNING_1 = "lightning1"
    LIGHTNING_2 = "lightning2"
    MAP_PINS = "mapPins"
    MAPLE_LEAF = "mapleLeaf"
    MAPLE_MUFFINS = "mapleMuffins"
    MARQUEE = "marquee"
    MARQUEE_TOOTHED = "marqueeToothed"
    MOONS = "moons"
    MOSAIC = "mosaic"
    MUSIC_NOTES = "musicNotes"
    NORTHWEST = "northwest"
    OVALS = "ovals"
    PACKAGES = "packages"
    PALMS_BLACK = "palmsBlack"
    PALMS_COLOR = "palmsColor"
    PAPER_CLIPS = "paperClips"
    PAPYRUS = "papyrus"
    PARTY_FAVOR = "partyFavor"
    PARTY_GLASS = "partyGlass"
    PENCILS = "pencils"
    PEOPLE = "people"
    PEOPLE_WAVING = "peopleWaving"
    PEOPLE_HATS = "peopleHats"
    POINSETTIAS = "poinsettias"
    POSTAGE_STAMP = "postageStamp"
    PUMPKIN_1 = "pumpkin1"
    PUSH_PIN_NOTE_2 = "pushPinNote2"
    PUSH_PIN_NOTE_1 = "pushPinNote1"
    PYRAMIDS = "pyramids"
    PYRAMIDS_ABOVE = "pyramidsAbove"
    QUADRANTS = "quadrants"
    RINGS = "rings"
    SAFARI = "safari"
    SAWTOOTH = "sawtooth"
    SAWTOOTH_GRAY = "sawtoothGray"
    SCARED_CAT = "scaredCat"
    SEATTLE = "seattle"
    SHADOWED_SQUARES = "shadowedSquares"
    SHARKS_TEETH = "sharksTeeth"
    SHOREBIRD_TRACKS = "shorebirdTracks"
    SKYROCKET = "skyrocket"
    SNOWFLAKE_FANCY = "snowflakeFancy"
    SNOWFLAKES = "snowflakes"
    SOMBRERO = "sombrero"
    SOUTHWEST = "southwest"
    STARS = "stars"
    STARS_TOP = "starsTop"
    STARS_3D = "stars3d"
    STARS_BLACK = "starsBlack"
    STARS_SHADOWED = "starsShadowed"
    SUN = "sun"
    SWIRLIGIG = "swirligig"
    TORN_PAPER = "tornPaper"
    TORN_PAPER_BLACK = "tornPaperBlack"
    TREES = "trees"
    TRIANGLE_PARTY = "triangleParty"
    TRIANGLES = "triangles"
    TRIANGLE_1 = "triangle1"
    TRIANGLE_2 = "triangle2"
    TRIANGLE_CIRCLE_1 = "triangleCircle1"
    TRIANGLE_CIRCLE_2 = "triangleCircle2"
    SHAPES_1 = "shapes1"
    SHAPES_2 = "shapes2"
    TWISTED_LINES_1 = "twistedLines1"
    TWISTED_LINES_2 = "twistedLines2"
    VINE = "vine"
    WAVELINE = "waveline"
    WEAVING_ANGLES = "weavingAngles"
    WEAVING_BRAID = "weavingBraid"
    WEAVING_RIBBON = "weavingRibbon"
    WEAVING_STRIPS = "weavingStrips"
    WHITE_FLOWERS = "whiteFlowers"
    WOODWORK = "woodwork"
    X_ILLUSIONS = "xIllusions"
    ZANY_TRIANGLES = "zanyTriangles"
    ZIG_ZAG = "zigZag"
    ZIG_ZAG_STITCH = "zigZagStitch"
    CUSTOM = "custom"


class SE_HEX_COLOR_AUTO(StrEnum):
    AUTO = "auto"


class SE_JC(StrEnum):
    START = "start"
    CENTER = "center"
    END = "end"
    BOTH = "both"
    MEDIUM_KASHIDA = "mediumKashida"
    DISTRIBUTE = "distribute"
    NUM_TAB = "numTab"
    HIGH_KASHIDA = "highKashida"
    LOW_KASHIDA = "lowKashida"
    THAI_DISTRIBUTE = "thaiDistribute"
    LEFT = "left"
    RIGHT = "right"


class SE_TEXT_ALIGNMENT(StrEnum):
    TOP = "top"
    CENTER = "center"
    BASELINE = "baseline"
    BOTTOM = "bottom"
    AUTO = "auto"


class SE_NUMBER_FORMAT(StrEnum):
    DECIMAL = "decimal"
    UPPER_ROMAN = "upperRoman"
    LOWER_ROMAN = "lowerRoman"
    UPPER_LETTER = "upperLetter"
    LOWER_LETTER = "lowerLetter"
    ORDINAL = "ordinal"
    CARDINAL_TEXT = "cardinalText"
    ORDINAL_TEXT = "ordinalText"
    HEX = "hex"
    CHICAGO = "chicago"
    IDEOGRAPH_DIGITAL = "ideographDigital"
    JAPANESE_COUNTING = "japaneseCounting"
    AIUEO = "aiueo"
    IROHA = "iroha"
    DECIMAL_FULL_WIDTH = "decimalFullWidth"
    DECIMAL_HALF_WIDTH = "decimalHalfWidth"
    JAPANESE_LEGAL = "japaneseLegal"
    JAPANESE_DIGITAL_TEN_THOUSAND = "japaneseDigitalTenThousand"
    DECIMAL_ENCLOSED_CIRCLE = "decimalEnclosedCircle"
    DECIMAL_FULL_WIDTH_2 = "decimalFullWidth2"
    AIUEO_FULL_WIDTH = "aiueoFullWidth"
    IROHA_FULL_WIDTH = "irohaFullWidth"
    DECIMAL_ZERO = "decimalZero"
    BULLET = "bullet"
    GANADA = "ganada"
    CHOSUNG = "chosung"
    DECIMAL_ENCLOSED_FULLSTOP = "decimalEnclosedFullstop"
    DECIMAL_ENCLOSED_PAREN = "decimalEnclosedParen"
    DECIMAL_ENCLOSED_CIRCLE_CHINESE = "decimalEnclosedCircleChinese"
    IDEOGRAPH_ENCLOSED_CIRCLE = "ideographEnclosedCircle"
    IDEOGRAPH_TRADITIONAL = "ideographTraditional"
    IDEOGRAPH_ZODIAC = "ideographZodiac"
    IDEOGRAPH_ZODIAC_TRADITIONAL = "ideographZodiacTraditional"
    TAIWANESE_COUNTING = "taiwaneseCounting"
    IDEOGRAPH_LEGAL_TRADITIONAL = "ideographLegalTraditional"
    TAIWANESE_COUNTING_THOUSAND = "taiwaneseCountingThousand"
    TAIWANESE_DIGITAL = "taiwaneseDigital"
    CHINESE_COUNTING = "chineseCounting"
    CHINESE_LEGAL_SIMPLIFIED = "chineseLegalSimplified"
    CHINESE_COUNTING_THOUSAND = "chineseCountingThousand"
    KOREAN_DIGITAL = "koreanDigital"
    KOREAN_COUNTING = "koreanCounting"
    KOREAN_LEGAL = "koreanLegal"
    KOREAN_DIGITAL_2 = "koreanDigital2"
    VIETNAMESE_COUNTING = "vietnameseCounting"
    RUSSIAN_LOWER = "russianLower"
    RUSSIAN_UPPER = "russianUpper"
    NONE = "none"
    NUMBER_IN_DASH = "numberInDash"
    HEBREW_1 = "hebrew1"
    HEBREW_2 = "hebrew2"
    ARABIC_ALPHA = "arabicAlpha"
    ARABIC_ABJAD = "arabicAbjad"
    HINDI_VOWELS = "hindiVowels"
    HINDI_CONSONANTS = "hindiConsonants"
    HINDI_NUMBERS = "hindiNumbers"
    HINDI_COUNTING = "hindiCounting"
    THAI_LETTERS = "thaiLetters"
    THAI_NUMBERS = "thaiNumbers"
    THAI_COUNTING = "thaiCounting"
    BAHT_TEXT = "bahtText"
    DOLLAR_TEXT = "dollarText"
    CUSTOM = "custom"


class SE_LEVEL_SUFFIX(StrEnum):
    TAB = "tab"
    SPACE = "space"
    NOTHING = "nothing"


class SE_TEXT_DIRECTION(StrEnum):
    TOP_TO_BOTTOM = "tb"
    RIGHT_TO_LEFT = "rl"
    LEFT_TO_RIGHT = "lr"
    TOP_TO_BOTTOM_VERTICAL = "tbV"
    RIGHT_TO_LEFT_VERTICAL = "rlV"
    LEFT_TO_RIGHT_VERTICAL = "lrV"
    BOTTOM_TO_TOP_LEFT_TO_RIGHT = "btLr"
    LEFT_TO_RIGHT_TOP_TO_BOTTOM = "lrTb"
    LEFT_TO_RIGHT_TOP_TO_BOTTOM_VERTICAL = "lrTbV"
    TOP_TO_BOTTOM_RIGHT_TO_LEFT = "tbRl"
    TOP_TO_BOTTOM_RIGHT_TO_LEFT_VERTICAL = "tbRlV"


class SE_HINT(StrEnum):
    DEFAULT = "default"
    EAST_ASIA = "eastASia"


class SE_THEME(StrEnum):
    MAJOR_EAST_ASIA = "majorEastAsia"
    MAJOR_BIDI = "majorBidi"
    MAJOR_ASCII = "majorAscii"
    MAJOR_H_ANSI = "majorHAnsi"
    MINOR_EAST_ASIA = "minorEastAsia"
    MINOR_BIDI = "minorBidi"
    MINOR_ASCII = "minorAscii"
    MINOR_H_ANSI = "minorHAnsi"


class SE_BR_TYPE(StrEnum):
    PAGE = "page"
    COLUMN = "column"
    TEXT_WRAPPING = "textWrapping"


class SE_BR_CLEAR(StrEnum):
    NONE = "none"
    LEFT = "left"
    RIGHT = "right"
    ALL = "all"


class SE_HEIGHT_RULE(StrEnum):
    AUTO = "auto"
    EXACT = "exact"
    AT_LEAST = "atLeast"


class SE_LINE_SPACING_RULE(StrEnum):
    AUTO = "auto"
    EXACT = "exact"
    AT_LEAST = "atLeast"


class SE_VERTICAL_JC(StrEnum):
    TOP = "top"
    CENTER = "center"
    BOTH = "both"
    BOTTOM = "bottom"


class SE_THEME_COLOR(StrEnum):
    DARK1 = "dark1"
    LIGHT1 = "light1"
    DARK2 = "dark2"
    LIGHT2 = "light2"
    ACCENT1 = "accent1"
    ACCENT2 = "accent2"
    ACCENT3 = "accent3"
    ACCENT4 = "accent4"
    ACCENT5 = "accent5"
    ACCENT6 = "accent6"
    HYPERLINK = "hyperlink"
    FOLLOWED_HYPERLINK = "followedHyperlink"
    NONE = "none"
    BACKGROUND1 = "background1"
    TEXT1 = "text1"
    BACKGROUND2 = "background2"
    TEXT2 = "text2"


class SE_JC_TABLE(StrEnum):
    CENTER = "center"
    END = "end"
    LEFT = "left"
    RIGHT = "right"
    START = "start"
